
import java.awt.BorderLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eljot
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        PanelCambiaPestañas.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        PanelCambiaPestañas = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        historialClinico = new javax.swing.JButton();
        Facturar = new javax.swing.JButton();
        agendarCitas = new javax.swing.JButton();
        crudClienteMascota = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion");
        setResizable(false);

        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelCambiaPestañasLayout = new javax.swing.GroupLayout(PanelCambiaPestañas);
        PanelCambiaPestañas.setLayout(PanelCambiaPestañasLayout);
        PanelCambiaPestañasLayout.setHorizontalGroup(
            PanelCambiaPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        PanelCambiaPestañasLayout.setVerticalGroup(
            PanelCambiaPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        Background.add(PanelCambiaPestañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 600));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0, 100));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/xddxd.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Light cat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Las mascotas son lindas :3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel2)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 254));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        historialClinico.setBackground(new java.awt.Color(255, 255, 254));
        historialClinico.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        historialClinico.setForeground(new java.awt.Color(47, 47, 47));
        historialClinico.setText("Historial clinico");
        historialClinico.setBorderPainted(false);
        historialClinico.setFocusPainted(false);
        historialClinico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                historialClinicoMouseMoved(evt);
            }
        });
        historialClinico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historialClinicoMouseExited(evt);
            }
        });
        historialClinico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialClinicoActionPerformed(evt);
            }
        });
        jPanel2.add(historialClinico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 50));

        Facturar.setBackground(new java.awt.Color(255, 255, 254));
        Facturar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Facturar.setForeground(new java.awt.Color(47, 47, 47));
        Facturar.setText("Facturar");
        Facturar.setBorderPainted(false);
        Facturar.setFocusPainted(false);
        Facturar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FacturarMouseMoved1(evt);
            }
        });
        Facturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FacturarMouseExited(evt);
            }
        });
        Facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturarActionPerformed(evt);
            }
        });
        jPanel2.add(Facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 50));

        agendarCitas.setBackground(new java.awt.Color(255, 255, 254));
        agendarCitas.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        agendarCitas.setForeground(new java.awt.Color(47, 47, 47));
        agendarCitas.setText("Agendar Citas");
        agendarCitas.setBorderPainted(false);
        agendarCitas.setFocusPainted(false);
        agendarCitas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                agendarCitasMouseMoved(evt);
            }
        });
        agendarCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agendarCitasMouseExited(evt);
            }
        });
        agendarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarCitasActionPerformed(evt);
            }
        });
        jPanel2.add(agendarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 50));

        crudClienteMascota.setBackground(new java.awt.Color(255, 255, 254));
        crudClienteMascota.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        crudClienteMascota.setForeground(new java.awt.Color(47, 47, 47));
        crudClienteMascota.setText("crudClienteMascota");
        crudClienteMascota.setBorderPainted(false);
        crudClienteMascota.setFocusPainted(false);
        crudClienteMascota.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                crudClienteMascotaMouseMoved(evt);
            }
        });
        crudClienteMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crudClienteMascotaMouseExited(evt);
            }
        });
        crudClienteMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudClienteMascotaActionPerformed(evt);
            }
        });
        jPanel2.add(crudClienteMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/avatar (2).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel6.setText("Tu usuario :d");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 180, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/jae-park-7GX5aICb5i4-unsplash (1) (1).jpg"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crudClienteMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crudClienteMascotaMouseExited
        // TODO add your handling code here:
        crudClienteMascota.setBackground(new java.awt.Color(255,255,254)); 
    }//GEN-LAST:event_crudClienteMascotaMouseExited

    private void crudClienteMascotaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crudClienteMascotaMouseMoved
        // TODO add your handling code here:
        crudClienteMascota.setBackground(new java.awt.Color(255,204,153));
    }//GEN-LAST:event_crudClienteMascotaMouseMoved

    private void agendarCitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarCitasMouseExited
        // TODO add your handling code here:
        agendarCitas.setBackground(new java.awt.Color(255,255,254)); 
    }//GEN-LAST:event_agendarCitasMouseExited

    private void agendarCitasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarCitasMouseMoved
        // TODO add your handling code here:
        agendarCitas.setBackground(new java.awt.Color(255,153,153));
    }//GEN-LAST:event_agendarCitasMouseMoved

    private void FacturarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturarMouseExited
        // TODO add your handling code here:
        Facturar.setBackground(new java.awt.Color(255,255,254)); 
    }//GEN-LAST:event_FacturarMouseExited

    private void FacturarMouseMoved1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturarMouseMoved1
        // TODO add your handling code here:
        Facturar.setBackground(new java.awt.Color(153,153,255));
    }//GEN-LAST:event_FacturarMouseMoved1

    private void historialClinicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialClinicoMouseExited
        // TODO add your handling code here:
        historialClinico.setBackground(new java.awt.Color(255,255,254)); 
    }//GEN-LAST:event_historialClinicoMouseExited

    private void historialClinicoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialClinicoMouseMoved
        // TODO add your handling code here:
        historialClinico.setBackground(new java.awt.Color(153,255,153));
    }//GEN-LAST:event_historialClinicoMouseMoved

    private void crudClienteMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudClienteMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crudClienteMascotaActionPerformed

    private void historialClinicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialClinicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historialClinicoActionPerformed

    private void agendarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendarCitasActionPerformed

    private void FacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturarActionPerformed
        // TODO add your handling code here:
        JPfractura miniFactura = new JPfractura(this);

        miniFactura.setSize(820,600);
        miniFactura.setLocation(0,0);
        PanelCambiaPestañas.setVisible(true);
        PanelCambiaPestañas.removeAll();
        PanelCambiaPestañas.add(miniFactura, BorderLayout.CENTER);
        PanelCambiaPestañas.revalidate();
        PanelCambiaPestañas.repaint();
    }//GEN-LAST:event_FacturarActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        PanelCambiaPestañas.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Facturar;
    private javax.swing.JPanel PanelCambiaPestañas;
    private javax.swing.JButton agendarCitas;
    private javax.swing.JButton crudClienteMascota;
    private javax.swing.JButton historialClinico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
