
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author eljot
 */
public class JFfractura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFfractura.class.getName());
    Facturas controladorFactura;
    /**
     * Creates new form JFfractura
     */
    public JFfractura() {
        initComponents();
       panelFactura.setBackground(new java.awt.Color(255, 255, 255,190));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelFactura = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLmascota = new javax.swing.JLabel();
        JLnombre = new javax.swing.JLabel();
        JLtelefono = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLprecio = new javax.swing.JLabel();
        JLiva = new javax.swing.JLabel();
        JLfecha = new javax.swing.JLabel();
        JLtotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFactura.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel2.setText("DATOS DEL CLIENTE");

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel3.setText("FACTURA");

        JLmascota.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLmascota.setText("FACTURA");

        JLnombre.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLnombre.setText("FACTURA");

        JLtelefono.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLtelefono.setText("FACTURA");

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel7.setText("DETALLE DE PAGO");

        JLprecio.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLprecio.setText("FACTURA");

        JLiva.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLiva.setText("FACTURA");

        JLfecha.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLfecha.setText("FACTURA");

        JLtotal.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLtotal.setText("FACTURA");

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel12.setText("--------------------------------------------------------------");

        jButton1.setBackground(new java.awt.Color(245, 245, 245));
        jButton1.setText("Generar pdf");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFacturaLayout = new javax.swing.GroupLayout(panelFactura);
        panelFactura.setLayout(panelFacturaLayout);
        panelFacturaLayout.setHorizontalGroup(
            panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturaLayout.createSequentialGroup()
                .addGroup(panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFacturaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(JLmascota)
                            .addComponent(JLnombre)
                            .addComponent(JLtelefono)
                            .addComponent(jLabel7)
                            .addComponent(JLprecio)
                            .addComponent(JLiva)
                            .addComponent(JLtotal)
                            .addComponent(jLabel12)))
                    .addGroup(panelFacturaLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(JLfecha))
                    .addGroup(panelFacturaLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel3))
                    .addGroup(panelFacturaLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        panelFacturaLayout.setVerticalGroup(
            panelFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(JLnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLtelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLmascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLprecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLiva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLfecha)
                .addContainerGap())
        );

        jPanel1.add(panelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 590, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/vecteezy_abstract-background-gradient-abstract-modern-background_6429746-1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controladorFactura.generarFacturaPdf();
        JOptionPane.showMessageDialog(this, "Se creo el pdf, este esta en la carpeta facturas " );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(245, 245, 245)); 
        jButton1.setForeground(new java.awt.Color(28, 28, 28));  
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(54, 52, 52));
        jButton1.setForeground(new java.awt.Color(245, 245, 245));
    }//GEN-LAST:event_jButton1MouseMoved
    public void getFactura(Facturas factura){
        this.controladorFactura = factura;
        JLnombre.setText("Nombre de cliente : "+controladorFactura.getNombreCliente());
        JLtelefono.setText("Telefeno de cliente : "+controladorFactura.getTelefonoCliente());
        JLmascota.setText("Nombre de mascota : "+controladorFactura.getNombreMascota());
        JLprecio.setText("Precio de servicio : "+String.format("%.2f", controladorFactura.getPrecio()));
        JLiva.setText("IVA : "+String.format("%.2f", controladorFactura.mostrariva()));
        JLtotal.setText("Total al pagar : "+String.format("%.2f", controladorFactura.mostrartotal()));
        JLfecha.setText(controladorFactura.getFecha());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFfractura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLfecha;
    private javax.swing.JLabel JLiva;
    private javax.swing.JLabel JLmascota;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLprecio;
    private javax.swing.JLabel JLtelefono;
    private javax.swing.JLabel JLtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelFactura;
    // End of variables declaration//GEN-END:variables
}
