
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author eljot
 */
public class JPfractura extends javax.swing.JPanel {

    /**
     * Creates new form JPfractura
     */
    private final Home parentHome;
    public JPfractura(Home parent) {
        initComponents();
        parentHome = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JCagenda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTservicio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JCmetodoDePago = new javax.swing.JComboBox<>();
        JCmascota = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        JCcliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        JTpago = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mascota : ");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        JCagenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        Background.add(JCagenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 260, -1));

        jLabel2.setText("Cliente");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Metodo de pago");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel6.setText("Selecione la agenda");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        JTservicio.setText("Ingrese el servicio");
        JTservicio.setBorder(null);
        JTservicio.setOpaque(true);
        JTservicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTservicioMousePressed(evt);
            }
        });
        Background.add(JTservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 300, 30));

        jButton1.setText("Generar el recibo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 240, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/xddxd.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Light cat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));
        Background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 300, -1));

        JCmetodoDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Efectivo","Tarjeta"}));
        Background.add(JCmetodoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 260, 20));

        JCmascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"gatito" }));
        JCmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCmascotaActionPerformed(evt);
            }
        });
        Background.add(JCmascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, -1));

        jLabel7.setText("Servicio :");
        Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        JCcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"jose","manuel" }));
        Background.add(JCcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 20));

        jLabel8.setText("Precio : ");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        JTpago.setText("Ingrese el precio");
        JTpago.setBorder(null);
        JTpago.setOpaque(true);
        JTpago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTpagoMousePressed(evt);
            }
        });
        Background.add(JTpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 300, 30));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 300, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTservicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTservicioMousePressed
        JTservicio.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_JTservicioMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombreCliente = (String) JCcliente.getSelectedItem();
        String nombreClienteMascota = (String) JCmascota.getSelectedItem();
        String servicio = JTservicio.getText();
        Double precio = Double.parseDouble(JTpago.getText());
        String cita = (String) JCagenda.getSelectedItem();
        String pago = (String) JCmetodoDePago.getSelectedItem();
        if(servicio.equalsIgnoreCase("efectivo")){
           
            return;
        }
        if(servicio.equalsIgnoreCase("tarjeta")){
            
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTpagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTpagoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTpagoMousePressed

    private void JCmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCmascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCmascotaActionPerformed


    
    private void seleccionarMetodoDePago(String metodo){
        if(metodo.equalsIgnoreCase("efectivo")){
            
            return;
        }
        if(metodo.equalsIgnoreCase("tarjeta")){
            return;
        }
        JOptionPane.showMessageDialog(null, "xddd");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> JCagenda;
    private javax.swing.JComboBox<String> JCcliente;
    private javax.swing.JComboBox<String> JCmascota;
    private javax.swing.JComboBox<String> JCmetodoDePago;
    private javax.swing.JTextField JTpago;
    private javax.swing.JTextField JTservicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
